site_name: techdocs
theme:
  name: material
  features:
    - navigation.sections
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode


docs_dir: docs
nav:
- Getting started: 'index.md'
- 'Tutorials': 
      - 'Background': 'tutorials/background.md'
      - 'Making notes': 'tutorials/making_notes.md'
      - 'Recording audio': 'tutorials/recording_audio.md'
- 'How to guide': 'how-to-guide/how_to_guide.md'
- 'Explanations': 'explanations/explanations.md'
- 'References': 'references/references.md'
- 'Help': 'help.md'


extra_css:
  - custom.css
  - stylesheets/extra.css
  - css/neoteroi-mkdocs.css

extra: 
      alternate:
      - name: English
        link: /docs/
        lang: en
      - name: Русский
        link: /ru/
        lang: ru
      - name: O'zbekcha
        link: /uz/
        lang: uz

markdown_extensions: 
- attr_list
- toc:
      permalink: true
- pymdownx.highlight
- pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
- pymdownx.highlight:
      pygments_lang_class: true

-  pymdownx.tasklist:
      custom_checkbox: true
- pymdownx.betterem
- admonition
- pymdownx.details
- pymdownx.superfences

  
copyright: "mukhammart"
